Use exec for entrypoint when starting zcashd
zcash-hackworks/docker-builds pull request #3
Opened 2019-11-25 18:53 UTC by benzcash

This change allows signals from the docker deamon to be received by the zcashd process.

Previously, stop signals where intercepted by the entrypont script, so a container stop event was not getting to zcashd, and it was being terminated without getting a chance to clean up.

2019-11-25 23:45 UTC, charlieok requested changes
Should the commits on this PR be squashed? There are four titled “Added cloudbuild.yaml” (the first actually does add cloudbuild.yaml, then the rest make changes to that file) followed by two titled “Added test builds for all images”.

2019-11-25 23:45 UTC, charlieok commented on cloudbuild.yaml
> +  - name: gcr.io/cloud-builders/docker
Is it intentional that all the entries in this 'steps' list have identical names?

2019-11-25 23:45 UTC, charlieok commented on cloudbuild.yaml
> +name: This is dumb
Reviews were requested on this PR but this last addition has me wondering if it's a work in progress or if it's intended to be merged

2019-11-25 23:46 UTC, mdr0id commented
utACK, please squash commits to clean log history

2019-11-26 17:38 UTC, charlieok approved these changes
ACK

2019-11-26 18:18 UTC, merged